version: '3.8'
x-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile

services:
  airflow-webserver:
    <<: *airflow-common
    volumes:
      - ./dags:/opt/airflow/dags
      - ./reference_config:/opt/airflow
      - ./data_crawl:/opt/airflow/data_crawl
      - ./dags/scripts:/opt/airflow/dags/scripts
    ports:
      - "8083:8080"
    command: >
      bash -c "(airflow db init && airflow users create --username airflow --password tungnei12345 --firstname Nguyen  --lastname Tung --role Admin --email tug1082003@gmail.com); airflow webserver & airflow scheduler"
    networks:
      - af_network

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: tungnei12345
    volumes:
      - af-minio-volume:/data
    command: server /data --console-address ":9001"
    networks:
      - af_network

  # For storing TIKI's data
  postgres-db:
    image: postgres:latest  # sử dụng phiên bản PostgreSQL mới nhất
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser         # tên người dùng cho PostgreSQL
      POSTGRES_PASSWORD: mypassword # mật khẩu cho PostgreSQL
      POSTGRES_DB: mydatabase       # tên database mặc định khi khởi tạo
    ports:
      - "5432:5432"  # mở cổng để có thể kết nối từ bên ngoài
    volumes:
      - postgres_data:/var/lib/postgresql/data  # lưu trữ dữ liệu để không mất khi khởi động lại container
    networks:
      - af_network
    
volumes:
  postgres_data:
  af-minio-volume:
  airflow.cfg:

networks:
  af_network:  # Đảm bảo mạng được định nghĩa