version: '3.8'
x-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile

services:
  db:
    image: postgres:16
    container_name: af_pg
    environment:
      POSTGRES_USER: postgres_db
      POSTGRES_PASSWORD: tungnei12345
      POSTGRES_DB: af_db
    volumes:
      - af-db-volume:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    networks:
      - af_network

  airflow-webserver:
    <<: *airflow-common
    volumes:
      - ./dags:/opt/airflow/dags
      - ./reference_config:/opt/airflow
      - ./data_crawl:/opt/airflow/data_crawl
      - ./dags/scripts:/opt/airflow/dags/scripts
    ports:
      - "8083:8080"
    command: >
      bash -c "(airflow db init && airflow users create --username airflow --password tungnei12345 --firstname Nguyen  --lastname Tung --role Admin --email tug1082003@gmail.com); airflow webserver & airflow scheduler"
    networks:
      - af_network

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: tungnei12345
    volumes:
      - af-minio-volume:/data
    command: server /data --console-address ":9001"
    networks:
      - af_network

  pg-tiki:  # For storing TIKI's data
    image: postgres:16
    container_name: pg-tiki
    environment:
      POSTGRES_DB: dw_tiki
      POSTGRES_USER: postgres_wh
      POSTGRES_PASSWORD: tungnei12345
    ports:
      - "45432:5432"
    volumes:
      - af-pg-tiki-volume:/var/lib/postgresql/data
    networks:
      - af_network
    
volumes:
  af-db-volume:
  af-minio-volume:
  af-pg-tiki-volume:
  airflow.cfg:

networks:
  af_network:  # Đảm bảo mạng được định nghĩa